DEFAULT_LOOKBACK_DAYS = 30
DEFAULT_REGION = "SA1"
DEFAULT_TABLE = "DISPATCHPRICE"

DROPPED_FCAS_COLUMNS = [
    "INTERVENTION",
    "RAISE6SECRRP",
    "RAISE60SECRRP",
    "RAISE5MINRRP",
    "RAISEREGRRP",
    "LOWER6SECRRP",
    "LOWER60SECRRP",
    "LOWER5MINRRP",
    "LOWERREGRRP",
    "PRICE_STATUS",
    "REGIONID",
]
